#+title: OSM-ru-lake-name-analyzer

Скрипты для анализ имён озёр России из OpenStreetMap на скорую руку: проверка пяти вариантов конвенций именования (наличие и позиция слова «озеро»).

https://community.openstreetmap.org/t/name/148024

Соответствие ~["natural"="water"]["water"="lake"]["name"]~ вариантам на 24.09.2026:

| Вариант 1 | 11396/39695 | 29% |
| Вариант 2 | 8644/39695  | 22% |
| Вариант 3 | 10370/39695 | 26% |
| Вариант 4 | 16347/39695 | 41% |
| Вариант 5 | 24690/39695 | 62% |

** Возможные варианты *(обновляется)*:

1. Строгое наличие слова "озеро" *в начале* ~name=~ для всех ~water=lake~.

   Примеры:

   - "озеро Байкал",
   - "озеро Ладожское",
   - "озеро Нижнее",
   - "озеро Сямозеро",
   - "[[https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D1%85%D0%BE%D0%B5_%D0%9E%D0%B7%D0%B5%D1%80%D0%BE_\(%D0%BE%D0%B7%D0%B5%D1%80%D0%BE\)][озеро Сухое Озеро]]", и т.д.

2. Свободное обязательное наличие слова "озеро":
   если имя собственное - существительное, то "озеро" ставится до него;
   если имя собственное - прилагательное, то "озеро" ставится после него.

   Примеры:

   - "озеро Байкал",
   - "Нижнее озеро",
   - "Ладожское озеро",
   - "озеро Сямозеро",
   - "[[https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D1%85%D0%BE%D0%B5_%D0%9E%D0%B7%D0%B5%D1%80%D0%BE_\(%D0%BE%D0%B7%D0%B5%D1%80%D0%BE\)][озеро Сухое Озеро]]", и т.д.

   /Так же существует мнение, что лишь 4 озера (Ладожское озеро, Онежское озеро, Псковское озеро, Чудское озеро) в русском языке должны иметь такой порядок; остальные озера с именами-прилагательными должны ставится в другом порядке (озеро Нижнее). Никаких подтверждений этому не найдено./

3. Смешанное наличие слова "озеро" в зависимости от названия озера (избежание тавтологии):

   Примеры:

   - "озеро Байкал",
   - "Нижнее озеро",
   - "Ладожское озеро",
   - "Сямозеро",
   - "[[https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D1%85%D0%BE%D0%B5_%D0%9E%D0%B7%D0%B5%D1%80%D0%BE_\(%D0%BE%D0%B7%D0%B5%D1%80%D0%BE\)][Сухое Озеро]]", и т.д.

   Проблемы варианта:

   - Слово озеро в имени собственном *не определяет* вид водоема, а лишь указывает на его исторический статус. В случае, когда такое имя не принадлежит озеру, тег `name=` должен содержать корректный вид водоёма.
     Пример: "[[https://ru.wikipedia.org/wiki/%D0%92%D1%8B%D0%B3%D0%BE%D0%B7%D0%B5%D1%80%D0%BE][водохранилище Выгозеро]]".

4. Наличие слова "озеро" только если оно является неотъемлемой частью названия, в соответствии с [[https://wiki.openstreetmap.org/wiki/RU:%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F][wiki/RU:Названия]]:

   #+begin_quote
   Вместе с тем, если родовое обозначение объекта (слово-категория) является неотъемлемой частью названия, то оно указываются в теге name и аналогичных ему. Правильно: name=Парк Горького, name=Химкинское водохранилище, name=Паб для всех. Неправильно: name=Горького, name=Химкинское, name=для всех). Собственная часть названия в этом случае обычно представляет собой прилагательное (чаще всего – притяжательное) и выполняет функцию согласованного определения (см. Определение (синтаксис) в Википедии) к слову-категории, отвечая на вопросы "какой", "чей", "чьего имени" и т.д.
   #+end_quote

   Примеры:

   - "Байкал",
   - "Нижнее озеро",
   - "Ладожское озеро",
   - "Сямозеро",
   - "[[https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D1%85%D0%BE%D0%B5_%D0%9E%D0%B7%D0%B5%D1%80%D0%BE_\(%D0%BE%D0%B7%D0%B5%D1%80%D0%BE\)][Сухое Озеро]]", и т.д.

   Проблемы варианта:

   - Озера-топонимы, совпадающие с именем более известного объекта. Не должно быть проблемой в контексте OSM.

5. Только имя собственное - без "озеро":
   Примеры:

   - "Байкал",
   - "Нижнее",
   - "Ладожское",
   - "Сямозеро",
   - "[[https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D1%85%D0%BE%D0%B5_%D0%9E%D0%B7%D0%B5%D1%80%D0%BE_\(%D0%BE%D0%B7%D0%B5%D1%80%D0%BE\)][Сухое Озеро]]", и т.д.

     
** Установка
pip install -r requirements.txt

** Использование
#+begin_src sh
python main.py           # Запрос к Overpass API, анализ имен
python main.py --local   # Не делать запрос; использовать локальный ru-lakes.csv
python main.py --refresh # Обновить ru-lakes.csv 
#+end_src

Каждый скрипт name-conditionsN.py создаёт names-conditionN.csv
с именами, удовлетворяющими условию N.

** Данные

© участники OpenStreetMap, данные распространяются по лицензии ODbL.
